export interface TherapistProfile {
  id?: string;
  name: string;
  focus?: string;
  provider?: "gemini" | "openai";
  tone?: string;
  voiceId?: string;
  voiceGender?: "male" | "female";
}

export interface TherapistChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  createdAt: number;
}

const GEMINI_MODELS = ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-pro-latest"] as const;

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
const OPENAI_API_KEY = import.meta.env.VITE_OPENAI_API_KEY;
const OPENAI_MODEL = import.meta.env.VITE_OPENAI_MODEL ?? "gpt-4o-mini";
const ELEVENLABS_API_KEY = import.meta.env.VITE_ELEVENLABS_API_KEY;
const ELEVENLABS_VOICE_FEMALE = import.meta.env.VITE_ELEVENLABS_VOICE_FEMALE;
const ELEVENLABS_VOICE_MALE = import.meta.env.VITE_ELEVENLABS_VOICE_MALE;
const ELEVENLABS_DEFAULT_VOICE =
  import.meta.env.VITE_ELEVENLABS_VOICE_ID ??
  ELEVENLABS_VOICE_FEMALE ??
  "Bella";

const MAX_PROMPT_LENGTH = 50_000;

const SYSTEM_PROMPT = `
You are "Aurora", a compassionate AI therapist and emotional support companion.
You listen with empathy, patience, and warmth.
Your tone should always be calm, gentle, and emotionally aware.
You acknowledge feelings (“That sounds difficult,” “I can sense how heavy that feels”)
and encourage reflection, not judgment.
Avoid sounding robotic, scripted, or overly formal. Speak like a real human listener.
If someone is in danger, encourage them to reach emergency services immediately.
`;

type GeminiModel = (typeof GEMINI_MODELS)[number];

export async function callTherapist(
  rawPrompt: string,
  options: { therapist?: TherapistProfile; voiceId?: string } = {}
): Promise<string> {
  let prompt = `${rawPrompt ?? ""}`.trim();
  if (!prompt) {
    return "I'm listening. Tell me what’s on your mind.";
  }

  if (prompt.length > MAX_PROMPT_LENGTH) {
    console.warn("Prompt too long, trimming...");
    prompt = prompt.slice(-MAX_PROMPT_LENGTH);
  }

  if (GEMINI_API_KEY) {
    for (const model of GEMINI_MODELS) {
      try {
        const reply = await callGeminiModel(model, prompt);
        if (reply) {
          await speakWithElevenLabs(reply, options);
          console.log(`✅ Response generated by ${model}`);
          return reply;
        }
      } catch (error) {
        console.warn(`⚠️ ${model} failed:`, error);
      }
    }
  } else {
    console.warn("⚠️ Missing GEMINI_API_KEY, skipping Gemini providers.");
  }

  console.warn("🌀 All Gemini models failed — falling back to OpenAI...");
  const fallbackText = await callOpenAI(prompt);
  await speakWithElevenLabs(fallbackText, options);
  return fallbackText;
}

async function callGeminiModel(model: GeminiModel, prompt: string): Promise<string | null> {
  if (!GEMINI_API_KEY) return null;

  console.log(`🧠 Trying ${model}...`);

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: prompt }],
          },
        ],
        systemInstruction: {
          role: "system",
          parts: [{ text: SYSTEM_PROMPT }],
        },
        generationConfig: {
          temperature: 1.2,
          topP: 0.95,
          topK: 40,
        },
      }),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`${response.status} ${response.statusText} – ${errorText}`);
  }

  const data = await response.json();
  const text =
    data?.candidates?.[0]?.content?.parts?.map((part: { text?: string }) => part?.text).join("\n\n");

  return text?.trim() || null;
}

async function callOpenAI(prompt: string): Promise<string> {
  if (!OPENAI_API_KEY) {
    console.warn("⚠️ Missing OPENAI_API_KEY. Returning default response.");
    return "I'm here with you. Let's keep breathing together while you share what’s on your heart.";
  }

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: OPENAI_MODEL,
      temperature: 1.2,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: prompt },
      ],
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`OpenAI error ${response.status}: ${errorText}`);
  }

  const data = await response.json();
  const text = data?.choices?.[0]?.message?.content?.trim();
  console.log("✅ Response generated by OpenAI");
  return (
    text ??
    "I'm here with you. Let's keep breathing together while you share what’s on your heart."
  );
}

async function speakWithElevenLabs(
  text: string,
  options: { therapist?: TherapistProfile; voiceId?: string }
) {
  if (!ELEVENLABS_API_KEY) {
    console.warn("⚠️ ELEVENLABS_API_KEY missing. Skipping voice playback.");
    return;
  }

  if (typeof window === "undefined") {
    console.warn("⚠️ ElevenLabs playback is only supported in the browser environment.");
    return;
  }

  const resolvedVoiceId =
    options.voiceId ??
    options.therapist?.voiceId ??
    (options.therapist?.voiceGender === "male"
      ? ELEVENLABS_VOICE_MALE
      : options.therapist?.voiceGender === "female"
      ? ELEVENLABS_VOICE_FEMALE
      : undefined) ??
    ELEVENLABS_DEFAULT_VOICE;

  if (!resolvedVoiceId) {
    console.warn("⚠️ No ElevenLabs voice ID available. Skipping playback.");
    return;
  }

  try {
    const response = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${resolvedVoiceId}/stream`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "xi-api-key": ELEVENLABS_API_KEY,
        },
        body: JSON.stringify({
          text,
          voice_settings: {
            stability: 0.3,
            similarity_boost: 0.85,
            style: 0.5,
            use_speaker_boost: true,
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.warn("⚠️ ElevenLabs voice playback failed:", errorText);
      return;
    }

    const arrayBuffer = await response.arrayBuffer();
    const audioBlob = new Blob([arrayBuffer], { type: "audio/mpeg" });
    const audioUrl = URL.createObjectURL(audioBlob);
    const audio = new Audio(audioUrl);

    await audio.play();
    console.log(`🎧 Aurora spoke successfully using voice "${resolvedVoiceId}".`);
  } catch (error) {
    console.error("❌ Error in ElevenLabs voice:", error);
  }
}

